# Generated by Django 3.2.7 on 2021-09-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210911_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym_workout',
            name='thumbnail',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
