# Generated by Django 3.2.7 on 2021-09-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_gym_workout_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym_workout',
            name='thumbnail',
            field=models.FileField(default=1, upload_to='gym_workout'),
            preserve_default=False,
        ),
    ]
